import Head from "next/head";

import { MainDoor } from "@/components";
import PostList from "@/components/PostList";
import { getPostsAndTags } from "@/apis";
import { useAppDispatch, useAppSelector } from "@/hooks/redux";
import { InitialPage } from "../types";
import { useEffect } from "react";
import { setPostsIDs } from "@/stores/slice";

const Home = ({ tags, posts }: InitialPage) => {
  const isMainDoor = useAppSelector((state) => state.isMainDoor);
  const dispatch = useAppDispatch();

  useEffect(() => {
    const postsIDs = posts.map(({ postId }) => postId).reverse();
    dispatch(setPostsIDs(postsIDs));
  }, [dispatch, posts]);

  return (
    <div>
      <Head>
        <title>Hong&apos;s blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isMainDoor && <MainDoor />}
      <PostList tags={tags} posts={posts} />
    </div>
  );
};

export async function getStaticProps() {
  const notionDatabaseID = process.env.NOTION_DATABASE || "";
  const { tags, posts } = await getPostsAndTags(notionDatabaseID);

  // await generateSiteMap(posts);

  return {
    props: {
      tags,
      posts,
    },
  };
}

export default Home;
